### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for DataParallel: Unexpected key(s) in state_dict: "module.albert.embeddings.position_ids"

### ISSUE THREAD

**Issue by mondal-anindita** [Open-Speech-EkStep/indic-punct#6]
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/anindita/Documents/Speech/indic-punct/src/punctuate/punctuate_text.py", line 32, in __init__
self.tokenizer, self.model, self.train_encoder, self.punctuation_dict = self.load_model_parameters()
File "/home/anindita/Documents/Speech/indic-punct/src/punctuate/punctuate_text.py", line 114, in load_model_parameters
model.load_state_dict(checkpoint['state_dict'])
File "/home/anindita/anaconda3/envs/ip10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
Unexpected key(s) in state_dict: "module.albert.embeddings.position_ids"

**Comment by janaab11** [comment]
@mondal-anindita this can be fixed by changing [this line](https://github.com/Open-Speech-EkStep/indic-punct/blob/11ba8fca6572bccd69bb991be0b9a1a8f05bd8dd/src/punctuate/punctuate_text.py#L114) in `src/punctuate/punctuate_text.py` to:
```python
model.load_state_dict(checkpoint['state_dict'], strict=False)
```

Reference is [here](https://stackoverflow.com/a/74457094) - tested to work locally.

**Comment by janaab11** [comment]
[here](https://github.com/facebookresearch/DPR/issues/165#issuecomment-1641698690) is an older reference - that explains what might be really going on here.
